apiVersion: apps/v1
kind: Deployment
metadata:
  name: yhishjhskhg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yhishjhskhg
  template:
    metadata:
      labels:
        app: yhishjhskhg
    spec:
      containers:
      - image: okteto.dev/yhishjhskhg:latest
        name: yhishjhskhg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "e758e331-7d97-4604-8558-b337697630bf"
        - name: Vless_Path
          value: "/b337697630bfvless"
        - name: Vmess_UUID
          value: "e758e331-7d97-4604-8558-b337697630bf"
        - name: Vmess_Path
          value: "/b337697630bfvmess"
        - name: Share_Path
          value: "/v2link"
